#### Load Block I:

In [3]:
import pandas as pd

I = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\19-20\ASI_DATA_2019_20_CSV\blkI201920.csv")
print(I.head())
print(I.columns)

   yr blk    AI01  I11      I13  I14          I15           I16        I17
0  20   I  100061    1   164000    9  20367535.08  3.156968e+09     155.00
1  20   I  100061    7  9994000    0         0.00  3.156968e+09       0.00
2  20   I  100070    1   137600   27       907.52  3.100781e+08  341676.36
3  20   I  100070    6  9922100    0         0.00  1.200000e+04       0.00
4  20   I  100070    7  9994000    0         0.00  3.100901e+08       0.00
Index(['yr', 'blk', 'AI01', 'I11', 'I13', 'I14', 'I15', 'I16', 'I17'], dtype='str')

#### Find energy_codes and Check Whether Energy Codes Exist

In [4]:
I["I13"].value_counts().head(50)
energy_codes = [
1101001,1101002,1101003,1101004,
1101005,1101006,1101007,1101099,
1102001,1102099,
1103000,1104000,
1202001,1202002,1202003,1202004,1202099,
1710001,1710002,1710003,1710005,
1710006,1710008,1710009,1710099
]

energy_df = I[I["I13"].isin(energy_codes)]
print("Rows found:", len(energy_df))
print(energy_df.head())

Rows found: 226
      yr blk    AI01  I11      I13  I14           I15           I16      I17
1476  20   I  103306    2  1101002   27  3.388000e+03  2.999354e+07  8852.87
2061  20   I  104833    2  1202004    9  7.214880e+08  2.707744e+10    37.53
2295  20   I  105190    1  1101002   27  6.409000e+03  5.346411e+07  8342.04
3410  20   I  107638    1  1101002   27  2.649304e+05  1.927490e+09  7275.46
3528  20   I  108138    1  1101002   27  9.932990e+03  6.423836e+07  6467.17

#### Build Fuel Table

In [5]:
print(I["I13"].dtype)
print(energy_df["I13"].value_counts())

int64
I13
1101002    187
1101001     14
1202003      5
1102001      5
1101004      3
1202001      3
1101003      3
1202004      2
1101007      1
1101006      1
1202099      1
1104000      1
Name: count, dtype: int64

#### Merge Block A With Factory Characteristics

In [6]:
A = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\19-20\ASI_DATA_2019_20_CSV\blkA201920.csv")

print(A.columns.tolist())

['yr', 'blk', 'a1', 'a2', 'a3', 'a4', 'a5', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12', 'bonus', 'pf', 'welfare', 'mwdays', 'nwdays', 'wdays', 'costop', 'expshare', 'mult']

#### Real Merge

In [7]:
merged = energy_df.merge(
    A[["a1","a4","a5","a7","costop","expshare","mult"]],
    left_on="AI01",
    right_on="a1",
    how="left"
)

print(merged.head())
print(merged.shape)
print(merged["a4"].value_counts().head(30))

   yr blk    AI01  I11      I13  I14           I15           I16      I17  \
0  20   I  103306    2  1101002   27  3.388000e+03  2.999354e+07  8852.87
1  20   I  104833    2  1202004    9  7.214880e+08  2.707744e+10    37.53
2  20   I  105190    1  1101002   27  6.409000e+03  5.346411e+07  8342.04
3  20   I  107638    1  1101002   27  2.649304e+05  1.927490e+09  7275.46
4  20   I  108138    1  1101002   27  9.932990e+03  6.423836e+07  6467.17

       a1    a4     a5  a7        costop  expshare  mult
0  103306  9999  23942   5  3.009254e+09         0   1.0
1  104833  9999  19201   6  6.759339e+11         0   1.0
2  105190  9999  23942   6  2.728905e+09         0   1.0
3  107638  9999  35102   8  2.574610e+09         0   1.0
4  108138  9999  13134   8  5.850094e+08         0   1.0
(226, 16)
a4
9999    226
Name: count, dtype: int64

#### Which Industries Use Coal/Gas

In [8]:
print(merged["a5"].value_counts().head(50))
print(sorted(merged["a5"].unique()))

a5
23941    30
23942    27
24105    18
24102    18
35102    17
24103    13
24101    11
19101    10
24104     9
10721     9
20119     8
19201     5
24109     5
35301     5
24202     3
24311     2
20111     2
20112     2
23939     2
35202     2
23943     2
23999     2
24204     2
13134     1
20121     1
22111     1
23949     1
24203     1
20116     1
19209     1
10402     1
35103     1
13114     1
20133     1
20118     1
20233     1
15129     1
23919     1
13121     1
20131     1
22201     1
24108     1
24319     1
17016     1
17093     1
Name: count, dtype: int64
[np.int64(10402), np.int64(10721), np.int64(13114), np.int64(13121), np.int64(13134), np.int64(15129), np.int64(17016), np.int64(17093), np.int64(19101), np.int64(19201), np.int64(19209), np.int64(20111), np.int64(20112), np.int64(20116), np.int64(20118), np.int64(20119), np.int64(20121), np.int64(20131), np.int64(20133), np.int64(20233), np.int64(22111), np.int64(22201), np.int64(23919), np.int64(23939), np.int64(23941), np.int64(23942), np.int64(23943), np.int64(23949), np.int64(23999), np.int64(24101), np.int64(24102), np.int64(24103), np.int64(24104), np.int64(24105), np.int64(24108), np.int64(24109), np.int64(24202), np.int64(24203), np.int64(24204), np.int64(24311), np.int64(24319), np.int64(35102), np.int64(35103), np.int64(35202), np.int64(35301)]

#### CBAM subset

In [9]:
cbam_codes = [
23941,23942,23943,23949,
24101,24102,24103,24104,24105,24108,24109,
24202,24203,24204,
20121
]

cbam_df = merged[
    merged["a5"].isin(cbam_codes)
]

print(cbam_df.shape)
print(cbam_df["a5"].value_counts())

(142, 16)
a5
23941    30
23942    27
24105    18
24102    18
24103    13
24101    11
24104     9
24109     5
24202     3
23943     2
24204     2
20121     1
23949     1
24203     1
24108     1
Name: count, dtype: int64

#### Create Fuel Labels

In [10]:
fuel_map = {
1101001:"Anthracite",
1101002:"Coal",
1101003:"Coal",
1101004:"Coal Ash",
1101006:"Coal Carbonisation",
1101007:"Coal Slack",
1102001:"Coal Briquettes",
1104000:"Lignite",
1202001:"Natural Gas",
1202003:"LNG",
1202004:"Regasified LNG",
1202099:"Natural Gas"
}

cbam_df["fuel_type"] = cbam_df["I13"].map(fuel_map)

print(cbam_df["fuel_type"].value_counts())

fuel_type
Coal                  125
Anthracite              7
Coal Briquettes         5
Coal Ash                3
Coal Slack              1
Coal Carbonisation      1
Name: count, dtype: int64

#### Load Block G

In [11]:
G = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\19-20\ASI_DATA_2019_20_CSV\blkG201920.csv")
print(G.columns.tolist())
print(G.head())

['yr', 'blk', 'AG01', 'G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11', 'G12']
   yr blk    AG01   G1            G2   G3         G4   G5   G6        G7   G8  \
0  20   G  100003  0.0  3.063770e+05  0.0        0.0  0.0  0.0       0.0  0.0
1  20   G  100005  0.0  0.000000e+00  0.0        0.0  0.0  0.0  942114.0  0.0
2  20   G  100006  0.0  1.628543e+09  0.0   163334.0  0.0  0.0       0.0  0.0
3  20   G  100007  0.0  3.091388e+08  0.0  7769993.0  0.0  0.0       0.0  0.0
4  20   G  100008  0.0  3.139040e+08  0.0        0.0  0.0  0.0       0.0  0.0

    G9        G10  G11  G12
0  0.0        0.0  0.0  0.0
1  0.0        0.0  0.0  0.0
2  0.0  2181059.0  0.0  0.0
3  0.0        0.0  0.0  0.0
4  0.0        0.0  0.0  0.0

#### Merge Block G with Your CBAM Dataset

In [12]:
merged2 = cbam_df.merge(
    G,
    left_on="AI01",
    right_on="AG01",
    how="left"
)

print(merged2.shape)
print(merged2.head())

(142, 32)
   yr_x blk_x    AI01  I11      I13  I14        I15           I16       I17  \
0    20     I  103306    2  1101002   27    3388.00  2.999354e+07   8852.87
1    20     I  105190    1  1101002   27    6409.00  5.346411e+07   8342.04
2    20     I  108554    1  1101001   27     191.00  3.230984e+06  16916.15
3    20     I  108871    1  1101002   27  206777.97  1.803042e+09   8719.70
4    20     I  108872    2  1101002   27  138800.07  1.137325e+09   8193.98

       a1  ...            G3           G4         G5        G6           G7  \
0  103306  ...  3.223820e+05    1146102.0        0.0       0.0  -24682376.0
1  105190  ...  0.000000e+00          0.0  3568478.0       0.0  -14243544.0
2  108554  ...  3.606888e+07          0.0        0.0       0.0    1253507.0
3  108871  ...  0.000000e+00  603108919.0  7060495.0   80950.0  -38526696.0
4  108872  ...  1.440230e+09          0.0        0.0  242328.0  100774673.0

          G8   G9          G10        G11          G12
0        0.0  0.0    2725292.0        0.0          0.0
1        0.0  0.0    1891165.0  3568478.0          0.0
2        0.0  0.0    9541538.0        0.0          0.0
3  1397459.0  0.0    4640759.0  7060495.0  112818099.0
4   850757.0  0.0  523285200.0        0.0          0.0

[5 rows x 32 columns]

#### Check Which G Variable Is Largest

In [13]:
print(
merged2[["G1","G2","G3","G4","G5","G6","G7","G8","G9","G10","G11","G12"]]
.describe()
)

                 G1            G2            G3            G4            G5  \
count  1.420000e+02  1.420000e+02  1.420000e+02  1.420000e+02  1.420000e+02
mean   5.890344e+07  5.107177e+08  1.980925e+08  1.433710e+09  2.682378e+07
std    2.297013e+08  1.539919e+09  1.389950e+09  8.787595e+09  9.923554e+07
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00 -4.302759e+07
25%    0.000000e+00  3.105805e+06  0.000000e+00  0.000000e+00  0.000000e+00
50%    0.000000e+00  3.319773e+07  0.000000e+00  0.000000e+00  0.000000e+00
75%    0.000000e+00  2.007266e+08  2.231511e+06  1.493715e+08  1.410782e+07
max    1.829476e+09  1.153013e+10  1.567748e+10  9.029202e+10  8.828799e+08

                 G6            G7            G8            G9           G10  \
count  1.420000e+02  1.420000e+02  1.420000e+02  1.420000e+02  1.420000e+02
mean   1.041255e+06 -3.814628e+07  1.279128e+07  2.989220e+05  7.383255e+07
std    6.584886e+06  5.898960e+08  8.660514e+07  3.376587e+06  2.301747e+08
min    0.000000e+00 -4.547700e+09  0.000000e+00  0.000000e+00  0.000000e+00
25%    0.000000e+00 -4.805876e+06  0.000000e+00  0.000000e+00  9.320345e+05
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  6.869860e+06
75%    0.000000e+00  2.611999e+07  2.555040e+05  0.000000e+00  4.154000e+07
max    6.887145e+07  1.697488e+09  9.031000e+08  4.023149e+07  2.087733e+09

                G11           G12
count  1.420000e+02  1.420000e+02
mean   2.745531e+08  5.680901e+06
std    9.136439e+08  5.410577e+07
min    0.000000e+00  0.000000e+00
25%    0.000000e+00  0.000000e+00
50%    0.000000e+00  0.000000e+00
75%    4.683418e+07  0.000000e+00
max    8.539250e+09  6.350221e+08

#### Compare With Cost of Production

In [14]:
print(G.columns)
for col in ["G1","G2","G3","G4","G5","G6","G7","G8","G9","G10","G11","G12"]:
    print(col, merged2[col].corr(merged2["costop"]))

Index(['yr', 'blk', 'AG01', 'G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8',
       'G9', 'G10', 'G11', 'G12'],
      dtype='str')
G1 0.030419276370914836
G2 0.7745256968918428
G3 0.4089886866548144
G4 0.5158551767235273
G5 0.21224173242192756
G6 0.18341844632915433
G7 -0.09728193326687314
G8 0.4652100927412502
G9 0.5122886881155015
G10 0.41105634295263915
G11 0.44131958733445575
G12 -0.0209109919015605

#### Load Block J

In [15]:
J = pd.read_csv(
r"C:\Users\hp\Downloads\CBAM PROJECT\19-20\ASI_DATA_2019_20_CSV\blkJ201920.csv"
)

print(J.columns.tolist())
print(J.head())

['yr', 'blk', 'AJ01', 'J11', 'J13', 'J14', 'J15', 'J16', 'J17', 'J18', 'J19', 'J110', 'J111', 'J112', 'J113']
   yr blk    AJ01  J11      J13  J14     J15    J16         J17  J18  J19  \
0  20   J  100002    1   325003   27  245.89  243.3  41772980.0  0.0  0.0
1  20   J  100002   11  9921100    0    0.00    0.0   1885510.0  0.0  0.0
2  20   J  100002   12  9995000    0    0.00    0.0  43658490.0  0.0  0.0
3  20   J  100003    1   325003   27  366.96   48.7  10538000.0  0.0  0.0
4  20   J  100003   12  9995000    0    0.00    0.0  10538000.0  0.0  0.0

       J110  J111       J112        J113
0       0.0   0.0  171693.30  42217666.0
1       0.0   0.0       0.00   1885510.0
2       0.0   0.0       0.00  44103176.0
3  355669.0   0.0  209082.77  76725014.0
4  355669.0   0.0       0.00  76725014.0

#### Merge Block J with Block A and 2nd Check

In [16]:
JA = J.merge(
    A[["a1","costop"]],
    left_on="AJ01",
    right_on="a1",
    how="left"
)
print("J17 :", JA["J17"].corr(JA["costop"]))
print("J113:", JA["J113"].corr(JA["costop"]))
print(
J[J["J13"].isin([9995000,9921100])]
[["J13","J17","J113"]]
.head(20)
)

J17 : 0.5396313024994591
J113: 0.5388055724212889
        J13           J17          J113
1   9921100  1.885510e+06  1.885510e+06
2   9995000  4.365849e+07  4.410318e+07
4   9995000  1.053800e+07  7.672501e+07
6   9995000  8.161923e+06  9.677709e+06
8   9995000  3.769026e+09  3.764277e+09
10  9995000  6.815166e+09  6.815166e+09
12  9995000  6.369441e+09  6.369441e+09
14  9995000  1.299783e+07  1.289882e+07
16  9995000  1.747105e+07  2.009306e+07
22  9995000  3.796213e+08  3.693654e+08
25  9995000  2.614927e+07  2.631713e+07
28  9995000  3.383880e+06  3.372280e+06
30  9995000  3.154625e+07  2.478894e+07
32  9995000  3.576377e+06  1.618011e+06
34  9995000  1.173326e+08  1.135366e+08
36  9995000  6.488210e+06  6.477910e+06
39  9995000  1.019683e+07  9.885205e+06
44  9995000  1.486990e+09  1.448068e+09
47  9995000  5.756168e+08  5.744713e+08
50  9995000  6.207178e+08  6.149319e+08

#### Third Check AND MERGE WITH CBAM DATA

In [17]:
output = (
    J.groupby("AJ01")["J17"]
    .sum()
    .reset_index()
)

output.columns = ["factory","output_value"]

print(output.head())
cbam_output = cbam_df.merge(
    output,
    left_on="AI01",
    right_on="factory",
    how="left"
)

print(cbam_output[["AI01","a5","output_value"]].head())

   factory  output_value
0   100002  8.731698e+07
1   100003  2.107600e+07
2   100005  1.632385e+07
3   100006  7.538053e+09
4   100007  1.363033e+10
     AI01     a5  output_value
0  103306  23942  1.547748e+10
1  105190  23942  1.166988e+10
2  108554  20121  3.987668e+10
3  108871  23942  3.324647e+10
4  108872  23941  2.306205e+10

#### J17 or J113

In [18]:
print("J17 :", JA["J17"].corr(JA["costop"]))
print("J113:", JA["J113"].corr(JA["costop"]))
output = (
    J.groupby("AJ01")["J17"]
    .sum()
    .reset_index()
)

output.columns = ["factory","output_value"]
print(output.columns.tolist())

J17 : 0.5396313024994591
J113: 0.5388055724212889
['factory', 'output_value']

#### Aggregate Fuel by Factory

In [19]:
fuel_by_factory = (
    cbam_df.groupby("AI01")
    .agg({
        "I15":"sum"
    })
    .reset_index()
)

fuel_by_factory.rename(
    columns={"I15":"fuel_quantity"},
    inplace=True
)

print(fuel_by_factory.head())

     AI01  fuel_quantity
0  103306        3388.00
1  105190        6409.00
2  108554         191.00
3  108871      206777.97
4  108872      138800.07

#### Merge Output

#### Add Industry and Export Variables

In [20]:
output = output.rename(
    columns={
        "AJ01":"factory",
        "J17":"output_value"
    }
)

firm_df = fuel_by_factory.merge(
    output,
    left_on="AI01",
    right_on="factory",
    how="left"
)
print(firm_df.head())
print(output.columns.tolist())

     AI01  fuel_quantity  factory  output_value
0  103306        3388.00   103306  1.547748e+10
1  105190        6409.00   105190  1.166988e+10
2  108554         191.00   108554  3.987668e+10
3  108871      206777.97   108871  3.324647e+10
4  108872      138800.07   108872  2.306205e+10
['factory', 'output_value']

In [21]:
firm_df = firm_df.merge(
    A[["a1","a5","a7","costop","expshare"]],
    left_on="AI01",
    right_on="a1",
    how="left"
)

#### Add Firm Characteristics

In [22]:
firm_df = firm_df.merge(
    A[["a1","a5","a7","costop","expshare"]],
    left_on="AI01",
    right_on="a1",
    how="left"
)

print(firm_df.head())

     AI01  fuel_quantity  factory  output_value    a1_x   a5_x  a7_x  \
0  103306        3388.00   103306  1.547748e+10  103306  23942     5
1  105190        6409.00   105190  1.166988e+10  105190  23942     6
2  108554         191.00   108554  3.987668e+10  108554  20121     8
3  108871      206777.97   108871  3.324647e+10  108871  23942     8
4  108872      138800.07   108872  2.306205e+10  108872  23941     8

       costop_x  expshare_x    a1_y   a5_y  a7_y      costop_y  expshare_y
0  3.009254e+09           0  103306  23942     5  3.009254e+09           0
1  2.728905e+09           0  105190  23942     6  2.728905e+09           0
2  1.701039e+10           0  108554  20121     8  1.701039e+10           0
3  1.094624e+10           0  108871  23942     8  1.094624e+10           0
4  9.147909e+09          18  108872  23941     8  9.147909e+09          18

#### Create Emissions

In [23]:
fuel_map = {
1101001:"Anthracite",
1101002:"Coal",
1101003:"Coal",
1101004:"Coal",
1101006:"Coal",
1101007:"Coal",
1102001:"Coal",
1104000:"Lignite",
1202001:"Natural Gas",
1202003:"LNG",
1202004:"LNG",
1202099:"Natural Gas"
}

cbam_df["fuel_type"] = cbam_df["I13"].map(fuel_map)

#### Emission Factors

In [24]:
ef = {
1101001:2.6,
1101002:2.42,
1101003:2.42,
1101004:2.42,
1101006:2.42,
1101007:2.42,
1102001:2.42,
1104000:2.1,
1202001:0.002,
1202003:0.002,
1202004:0.002,
1202099:0.002
}

cbam_df["ef"] = cbam_df["I13"].map(ef)

cbam_df["co2_proxy"] = cbam_df["I15"] * cbam_df["ef"]

#### Aggregate Emissions

In [25]:
emissions = (
    cbam_df.groupby("AI01")["co2_proxy"]
    .sum()
    .reset_index()
)
print(emissions.head())

     AI01    co2_proxy
0  103306    8198.9600
1  105190   15509.7800
2  108554     496.6000
3  108871  500402.6874
4  108872  335896.1694

#### Merge Emissions Into Firm Dataset

In [26]:
firm_df = firm_df.merge(
    emissions,
    on="AI01",
    how="left"
)

#### Compute Carbon Intensity

In [27]:
firm_df["carbon_intensity"] = (
    firm_df["co2_proxy"] /
    firm_df["output_value"]
)

#### First Research Result

In [28]:
firm_df = firm_df.rename(columns={
    "a5_x": "a5",
    "a7_x": "state",
    "costop_x": "costop",
    "expshare_x": "expshare",
    "emissions_proxy": "co2_proxy"
})

print(firm_df.columns.tolist())

['AI01', 'fuel_quantity', 'factory', 'output_value', 'a1_x', 'a5', 'state', 'costop', 'expshare', 'a1_y', 'a5_y', 'a7_y', 'costop_y', 'expshare_y', 'co2_proxy', 'carbon_intensity']

In [29]:
firm_df.groupby("a5")["carbon_intensity"] \
       .mean() \
       .sort_values(ascending=False)

a5
24204    3.916150e-05
24102    3.878959e-05
24108    2.806231e-05
24103    2.305176e-05
24105    2.248333e-05
24101    1.992599e-05
23941    1.778349e-05
24109    1.757636e-05
24104    1.745764e-05
23943    1.561272e-05
23942    1.461970e-05
24203    7.369770e-06
23949    2.630630e-06
24202    2.144261e-06
20121    1.245339e-08
Name: carbon_intensity, dtype: float64

#### Clean Firm Dataset

In [30]:
firm_df.columns

Index(['AI01', 'fuel_quantity', 'factory', 'output_value', 'a1_x', 'a5',
       'state', 'costop', 'expshare', 'a1_y', 'a5_y', 'a7_y', 'costop_y',
       'expshare_y', 'co2_proxy', 'carbon_intensity'],
      dtype='str')

#### Vulnerability Score

In [31]:
firm_df["vulnerability"] = (
    firm_df["co2_proxy"] /
    firm_df["costop"]
    )
print(firm_df[["AI01","a5","vulnerability"]].head())

     AI01     a5  vulnerability
0  103306  23942   2.724582e-06
1  105190  23942   5.683517e-06
2  108554  20121   2.919393e-08
3  108871  23942   4.571457e-05
4  108872  23941   3.671835e-05

#### Examine Exporters

In [32]:
firm_df["exporter"] = (
    firm_df["expshare"] > 0
).astype(int)

print(firm_df["exporter"].value_counts())

exporter
0    126
1     10
Name: count, dtype: int64

#### Check Export Distribution

In [33]:
print(firm_df["expshare"].describe())
print(
    (firm_df["expshare"] > 0).sum()
)

count    136.000000
mean       1.522059
std        6.653283
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max       41.000000
Name: expshare, dtype: float64
10

#### Top Exporters

In [34]:
firm_df[
    ["AI01","a5","expshare","carbon_intensity"]
].sort_values(
    "expshare",
    ascending=False
).head(20)

      AI01     a5  expshare  carbon_intensity
17  112453  24202        41      1.209524e-08
74  126699  24103        40      1.180884e-05
72  126695  24109        35      1.799322e-06
15  109043  24101        27      2.491753e-06
16  109068  24203        24      7.369770e-06
4   108872  23941        18      1.456489e-05
34  120103  24104         9      1.723311e-05
32  120061  24103         7      6.057666e-06
73  126696  24102         5      1.205781e-06
6   108877  23949         1      2.630630e-06
7   108878  23941         0      3.121410e-05
5   108876  23942         0      2.736246e-05
1   105190  23942         0      1.329044e-06
0   103306  23942         0      5.297347e-07
2   108554  20121         0      1.245339e-08
3   108871  23942         0      1.505130e-05
14  108907  23941         0      9.882619e-06
13  108906  23941         0      1.555087e-05
18  114671  23942         0      1.124416e-08
19  118971  24105         0      3.247655e-05

#### Carbon Intensity of Exporters vs Non-Exporters

In [35]:
firm_df.groupby(
    firm_df["expshare"]>0
)["carbon_intensity"].mean()

expshare
False    0.000022
True     0.000007
Name: carbon_intensity, dtype: float64

#### Sector-Level Vulnerability

In [36]:
firm_df["vulnerability"] = (
    firm_df["co2_proxy"] /
    firm_df["costop"]
)
firm_df.groupby("a5")["vulnerability"].mean()

a5
20121    2.919393e-08
23941    5.000596e-05
23942    4.230405e-05
23943    3.317132e-05
23949    9.935602e-06
24101    3.585873e-05
24102    8.461407e-05
24103    4.966204e-05
24104    3.895008e-05
24105    4.361899e-05
24108    5.369943e-05
24109    3.866706e-05
24202    3.854310e-06
24203    1.888773e-05
24204    8.841979e-05
Name: vulnerability, dtype: float64

#### CO₂ proxy

In [37]:
firm_df.rename(
    columns={"co2_proxy":"emissions_proxy"},
    inplace=True
)

In [38]:
print(firm_df.columns)

Index(['AI01', 'fuel_quantity', 'factory', 'output_value', 'a1_x', 'a5',
       'state', 'costop', 'expshare', 'a1_y', 'a5_y', 'a7_y', 'costop_y',
       'expshare_y', 'emissions_proxy', 'carbon_intensity', 'vulnerability',
       'exporter'],
      dtype='str')

In [39]:
print((firm_df["a5_x"] == firm_df["a5_y"]).all())

KeyError: 'a5_x'

In [40]:
firm_df.groupby("a5_x")["carbon_intensity"].mean().sort_values(ascending=False)

KeyError: 'a5_x'

In [41]:
firm_df = firm_df.rename(columns={
    "a5_x":"a5",
    "a7_x":"state",
    "costop_x":"costop",
    "expshare_x":"expshare"
})

In [42]:
firm_df = firm_df.drop(
    columns=[
        "a1_y","a5_y","a7_y",
        "costop_y","expshare_y"
    ]
)

In [43]:
print(firm_df.columns)

Index(['AI01', 'fuel_quantity', 'factory', 'output_value', 'a1_x', 'a5',
       'state', 'costop', 'expshare', 'emissions_proxy', 'carbon_intensity',
       'vulnerability', 'exporter'],
      dtype='str')

In [44]:
firm_df.to_csv(
    "CBAM_2019_20_firm_level.csv",
    index=False
)

### Filter CBAM codes

In [45]:
import pandas as pd

A = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\19-20\ASI_DATA_2019_20_CSV\blkA201920.csv")
B = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\19-20\ASI_DATA_2019_20_CSV\blkB201920.csv")
E = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\19-20\ASI_DATA_2019_20_CSV\blkE201920.csv")
F = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\19-20\ASI_DATA_2019_20_CSV\blkF201920.csv")
G = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\19-20\ASI_DATA_2019_20_CSV\blkG201920.csv")
J = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\19-20\ASI_DATA_2019_20_CSV\blkJ201920.csv")

In [46]:
cbam_codes = [
    24101,24102,24103,24104,24105,24106,24107,
    24201,24202,24203,24204,24209,
    23941,23942,
    20121,20122,20129
]
cbam = A[A["a5"].isin(cbam_codes)]

print(cbam.shape)
print(cbam["a5"].value_counts())

(2324, 22)
a5
24105    364
24103    267
24202    225
23942    181
24209    181
24101    150
20129    134
24102    126
23941    122
24104    104
24201    102
24203     92
20121     91
24106     91
20122     62
24204     23
24107      9
Name: count, dtype: int64

In [47]:
cbam = A[A["a5"].isin(cbam_codes)]
print(cbam.shape)
print(cbam["a5"].value_counts())
exporters = cbam[cbam["expshare"] > 0]
print(E.columns.tolist())
print(E.head())

print(J.columns.tolist())
print(J.head())

(2324, 22)
a5
24105    364
24103    267
24202    225
23942    181
24209    181
24101    150
20129    134
24102    126
23941    122
24104    104
24201    102
24203     92
20121     91
24106     91
20122     62
24204     23
24107      9
Name: count, dtype: int64
['yr', 'blk', 'AE01', 'E11', 'E13', 'E14', 'E15', 'E16', 'E17', 'E18']
   yr blk    AE01  E11  E13  E14  E15  E16  E17      E18
0  20   E  100001    1    0    0    0    0    0      0.0
1  20   E  100001    2    0    0    0    0    0      0.0
2  20   E  100001    4    0    0    0    0    0      0.0
3  20   E  100001    6    0    0    0    0    0      0.0
4  20   E  100001    7    0  366  366    1  366  95000.0
['yr', 'blk', 'AJ01', 'J11', 'J13', 'J14', 'J15', 'J16', 'J17', 'J18', 'J19', 'J110', 'J111', 'J112', 'J113']
   yr blk    AJ01  J11      J13  J14     J15    J16         J17  J18  J19  \
0  20   J  100002    1   325003   27  245.89  243.3  41772980.0  0.0  0.0
1  20   J  100002   11  9921100    0    0.00    0.0   1885510.0  0.0  0.0
2  20   J  100002   12  9995000    0    0.00    0.0  43658490.0  0.0  0.0
3  20   J  100003    1   325003   27  366.96   48.7  10538000.0  0.0  0.0
4  20   J  100003   12  9995000    0    0.00    0.0  10538000.0  0.0  0.0

       J110  J111       J112        J113
0       0.0   0.0  171693.30  42217666.0
1       0.0   0.0       0.00   1885510.0
2       0.0   0.0       0.00  44103176.0
3  355669.0   0.0  209082.77  76725014.0
4  355669.0   0.0       0.00  76725014.0

### Employment Summary:

In [48]:
emp = (
    E.groupby("AE01")[["E13","E15","E18"]]
    .sum()
    .reset_index()
)

print(emp.head())
print(emp.shape)

     AE01     E13     E15           E18
0  100001       0     732  1.900000e+05
1  100002   35476   36560  1.248123e+07
2  100003    7288    7704  2.931320e+06
3  100005    6172    6172  1.732244e+06
4  100006  532098  532098  1.143298e+09
(56087, 4)

### Output Summary:

In [49]:
output = (
    J[J["J13"] == 9995000]
    [["AJ01","J113"]]
    .rename(
        columns={
            "AJ01":"factory",
            "J113":"output_value"
        }
    )
)

print(output.head())
print(output.shape)

    factory  output_value
2    100002  4.410318e+07
4    100003  7.672501e+07
6    100005  9.677709e+06
8    100006  3.764277e+09
10   100007  6.815166e+09
(45708, 2)

### Filter exporters:

In [50]:
exporters = cbam[cbam["expshare"] > 0]

print(exporters.shape)

print(exporters["expshare"].describe())

print(
    exporters[["a1","a5","expshare"]]
    .sort_values("expshare", ascending=False)
    .head(20)
)

(44, 22)
count     44.000000
mean      23.090909
std       25.026329
min        1.000000
25%        6.500000
50%       14.500000
75%       28.250000
max      100.000000
Name: expshare, dtype: float64
           a1     a5  expshare
11221  112473  24209       100
31503  136345  24104        92
54453  210823  24106        73
11274  112528  24105        68
18272  120101  24104        65
27666  131487  20129        54
57503  213873  24201        53
11201  112453  24202        41
54890  211260  24103        40
24001  126699  24103        40
23984  126679  24106        32
8104   109043  24101        27
17371  119036  24107        26
59530  215900  24104        24
8122   109068  24203        24
42033  152464  24104        23
23999  126697  24106        22
23914  126601  23941        19
7977   108872  23941        18
24082  126790  24201        18

### Merge everything:

In [51]:
final_2019 = (
    exporters
    .merge(
        emp,
        left_on="a1",
        right_on="AE01",
        how="left"
    )
    .merge(
        output,
        left_on="a1",
        right_on="factory",
        how="left"
    )
)

print(final_2019.shape)

print(
    final_2019[
        ["E13","E15","E18","output_value"]
    ].isna().sum()
)

final_2019.head()

(44, 28)
E13             0
E15             0
E18             0
output_value    0
dtype: int64

,yr,blk,a1,a2,a3,a4,a5,a7,a8,a9,...,wdays,costop,expshare,mult,AE01,E13,E15,E18,factory,output_value
0,20,A,102013,99999,1,9999,24103,3,99,2,...,347,3.629252e+09,1,1.0,102013,433012,433012,1.881837e+08,102013,3.715064e+09
1,20,A,105270,99999,1,9999,24202,6,99,2,...,302,1.445604e+09,13,1.0,105270,139703,139703,1.387626e+08,105270,1.576325e+09
2,20,A,108872,99999,1,9999,23941,8,99,2,...,357,9.147909e+09,18,1.0,108872,646767,646767,1.441425e+09,108872,8.576613e+09
3,20,A,109043,99999,1,9999,24101,8,99,1,...,355,6.267033e+09,27,1.0,109043,596542,596542,7.232797e+08,109043,1.020846e+10
4,20,A,109053,99999,1,9999,24105,8,99,2,...,355,1.210633e+10,7,1.0,109053,528444,528444,7.527299e+08,109053,1.247257e+10

In [52]:
final_2019.to_excel(
    "CBAM_Exporters_2019_20.xlsx",
    index=False
)

### Verify whether you have Block I for ALL years

In [53]:
print(I.columns.tolist())
print(I.head())

['yr', 'blk', 'AI01', 'I11', 'I13', 'I14', 'I15', 'I16', 'I17']
   yr blk    AI01  I11      I13  I14          I15           I16        I17
0  20   I  100061    1   164000    9  20367535.08  3.156968e+09     155.00
1  20   I  100061    7  9994000    0         0.00  3.156968e+09       0.00
2  20   I  100070    1   137600   27       907.52  3.100781e+08  341676.36
3  20   I  100070    6  9922100    0         0.00  1.200000e+04       0.00
4  20   I  100070    7  9994000    0         0.00  3.100901e+08       0.00

In [54]:
print(sorted(I["I13"].unique())[:100])

[np.int64(111100), np.int64(111200), np.int64(112100), np.int64(112200), np.int64(115100), np.int64(115200), np.int64(117100), np.int64(117200), np.int64(121300), np.int64(123100), np.int64(123200), np.int64(123500), np.int64(124100), np.int64(124900), np.int64(125100), np.int64(125300), np.int64(125400), np.int64(126000), np.int64(129003), np.int64(129099), np.int64(131400), np.int64(131700), np.int64(131900), np.int64(132100), np.int64(132400), np.int64(132900), np.int64(134200), np.int64(134900), np.int64(135100), np.int64(135200), np.int64(135300), np.int64(135400), np.int64(135900), np.int64(136000), np.int64(137100), np.int64(137200), np.int64(137400), np.int64(137500), np.int64(137600), np.int64(137900), np.int64(139900), np.int64(141200), np.int64(142200), np.int64(143200), np.int64(144100), np.int64(144400), np.int64(144999), np.int64(145000), np.int64(146000), np.int64(149100), np.int64(159100), np.int64(159200), np.int64(161001), np.int64(162002), np.int64(162099), np.int64(164000), np.int64(165100), np.int64(165200), np.int64(165300), np.int64(165400), np.int64(165500), np.int64(165600), np.int64(165700), np.int64(165800), np.int64(165900), np.int64(169000), np.int64(170102), np.int64(170103), np.int64(170199), np.int64(170399), np.int64(170400), np.int64(170901), np.int64(170902), np.int64(170903), np.int64(180100), np.int64(191302), np.int64(192100), np.int64(192200), np.int64(193007), np.int64(193008), np.int64(193010), np.int64(193013), np.int64(193099), np.int64(195000), np.int64(196200), np.int64(196300), np.int64(199000), np.int64(241100), np.int64(291000), np.int64(294100), np.int64(294200), np.int64(294300), np.int64(294402), np.int64(295100), np.int64(295300), np.int64(295400), np.int64(311000), np.int64(312001), np.int64(312099), np.int64(313000)]

In [55]:
fuel19 = (
    I.groupby("I13")["I16"]
    .sum()
    .sort_values(ascending=False)
)

fuel19.head(30)

I13
9994000    1.547668e+13
1201000    5.354396e+12
1639001    1.794154e+12
1101002    8.076500e+11
9922100    5.718795e+11
4132099    4.645312e+11
1424004    3.892622e+11
1202003    3.167683e+11
1632001    2.490215e+11
2153500    2.342247e+11
1421000    1.380020e+11
2153100    1.298995e+11
4912999    1.209301e+11
3411071    1.056711e+11
2153300    9.895535e+10
4132003    9.335661e+10
4121101    8.115704e+10
1101006    6.266330e+10
3934003    6.167974e+10
4740100    6.162988e+10
4714099    5.967403e+10
3418001    5.271757e+10
3310007    5.195834e+10
3423200    5.179070e+10
1639006    4.567137e+10
3350003    4.289143e+10
4713099    4.150498e+10
3338007    4.115608e+10
3411072    3.980058e+10
3935001    3.963772e+10
Name: I16, dtype: float64

In [56]:
codes = pd.DataFrame(
    sorted(I["I13"].dropna().unique()),
    columns=["item_code"]
)

codes.to_excel("ASI_I_block_codes.xlsx", index=False)

print("Saved")

Saved