### Load Data

In [5]:
import pandas as pd

A = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\23-24\ASI_DATA_2023_24_CSV\blkA202324.csv")
B = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\23-24\ASI_DATA_2023_24_CSV\blkB202324.csv")
E = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\23-24\ASI_DATA_2023_24_CSV\blkE202324.csv")
F = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\23-24\ASI_DATA_2023_24_CSV\blkF202324.csv")
G = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\23-24\ASI_DATA_2023_24_CSV\blkG202324.csv")
J = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\23-24\ASI_DATA_2023_24_CSV\blkJ202324.csv")

### Inspect Blocks

In [6]:
for name, df in {
    "A":A,
    "B":B,
    "E":E,
    "F":F,
    "G":G,
    "J":J
}.items():

    print("\n"+"="*80)
    print(f"BLOCK {name}")
    print("="*80)

    print("Shape:",df.shape)
    print("Columns:",df.columns.tolist())
    print(df.head())

================================================================================
BLOCK A
================================================================================
Shape: (68641, 22)
Columns: ['yr', 'blk', 'a1', 'a2', 'a3', 'a4', 'a5', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12', 'bonus', 'pf', 'welfare', 'mwdays', 'nwdays', 'wdays', 'costop', 'expshare', 'mult']
   yr blk      a1     a2  a3    a4     a5  a7  a8  a9  ...  a12     bonus  \
0  24   A  100001  99999   1  9999  12007   1  99   2  ...    4       0.0
1  24   A  100002  99999   1  9999  12007   1  99   2  ...    1       0.0
2  24   A  100003  99999   1  9999  12007   1  99   2  ...    3       0.0
3  24   A  100004  99999   1  9999  12007   1  99   2  ...    1       0.0
4  24   A  100005  99999   1  9999  12007   1  99   2  ...    1  242900.0

        pf  welfare  mwdays  nwdays  wdays      costop  expshare  mult
0      0.0      0.0       0       0      0         0.0         0   1.0
1      0.0      0.0     306       0    306  11466542.0         0   1.0
2      0.0      0.0       0       0      0         0.0         0   1.0
3      0.0   3200.0      87       0     87   6004550.0         0   1.0
4  43666.0      0.0     305       0    305  28315123.0         0   1.0

[5 rows x 22 columns]

================================================================================
BLOCK B
================================================================================
Shape: (68641, 13)
Columns: ['yr', 'blk', 'ab01', 'b02', 'b03', 'b04', 'b05', 'b06f', 'b06t', 'b07', 'b08', 'b09', 'b11']
   yr blk    ab01  b02                    b03  b04   b05  b06f   b06t  b07  \
0  24   B  100001    7  999999999999999999999    2     0     4  32024    0
1  24   B  100002    1  999999999999999999999    2  2017     4  32024   12
2  24   B  100003    1  999999999999999999999    2  2020     4  32024    0
3  24   B  100004    1  999999999999999999999    2  2019     4  32024    5
4  24   B  100005    1  999999999999999999999    2  2019     4  32024   12

   b08  b09  b11
0    2    3    2
1    2    3    2
2    2    3    2
3    2    3    2
4    2    3    2

================================================================================
BLOCK E
================================================================================
Shape: (596862, 10)
Columns: ['yr', 'blk', 'AE01', 'EI1', 'EI3', 'EI4', 'EI5', 'EI6', 'EI7', 'EI8']
   yr blk    AE01  EI1   EI3  EI4   EI5  EI6   EI7       EI8
0  24   E  100002    1  1752    0  1752    6  2103  545000.0
1  24   E  100002    2     0    0     0    0     0       0.0
2  24   E  100002    3     0    0     0    0     0       0.0
3  24   E  100002    5     0    0     0    0     0       0.0
4  24   E  100002    7   295    0   295    1   366  175500.0

================================================================================
BLOCK F
================================================================================
Shape: (58862, 17)
Columns: ['yr', 'blk', 'AF01', 'F1', 'F2A', 'F2B', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13']
   yr blk    AF01   F1      F2A      F2B        F3   F4        F5   F6   F7  \
0  24   F  100002  0.0      0.0      0.0  321794.0  0.0  423220.0  0.0  0.0
1  24   F  100004  0.0  13672.0  15994.0   46480.0  0.0   43601.0  0.0  0.0
2  24   F  100005  0.0   3540.0  33900.0  189107.0  0.0  130295.0  0.0  0.0
3  24   F  100006  0.0      0.0      0.0   28845.0  0.0       0.0  0.0  0.0
4  24   F  100007  0.0      0.0      0.0  470566.0  0.0  170134.0  0.0  0.0

        F8       F9        F10  F11      F12  F13
0      0.0  37500.0  1971914.0  0.0      0.0  0.0
1      0.0  28190.0   179471.0  0.0      0.0  0.0
2  28308.0  10604.0  2191952.0  0.0   1273.0  0.0
3      0.0      0.0        0.0  0.0      0.0  0.0
4      0.0      0.0  2763308.0  0.0  15000.0  0.0

================================================================================
BLOCK G
================================================================================
Shape: (54133, 15)
Columns: ['yr', 'blk', 'AG01', 'G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11', 'G12']
   yr blk    AG01   G1   G2   G3   G4   G5   G6         G7   G8   G9      G10  \
0  24   G  100004  0.0  0.0  0.0  0.0  0.0  0.0   -30070.0  0.0  0.0      0.0
1  24   G  100005  0.0  0.0  0.0  0.0  0.0  0.0 -1077471.0  0.0  0.0  18505.0
2  24   G  100006  0.0  0.0  0.0  0.0  0.0  0.0        0.0  0.0  0.0  15830.0
3  24   G  100007  0.0  0.0  0.0  0.0  0.0  0.0        0.0  0.0  0.0   6502.0
4  24   G  100008  0.0  0.0  0.0  0.0  0.0  0.0        0.0  0.0  0.0  10172.0

   G11  G12
0  0.0  0.0
1  0.0  0.0
2  0.0  0.0
3  0.0  0.0
4  0.0  0.0

================================================================================
BLOCK J
================================================================================
Shape: (147421, 15)
Columns: ['yr', 'blk', 'AJ01', 'J11', 'J13', 'J14', 'J15', 'J16', 'J17', 'J18', 'J19', 'J110', 'J111', 'J112', 'J113']
   yr blk    AJ01  J11      J13  J14     J15     J16         J17  J18  J19  \
0  24   J  100002    1   325003   27   82.39   82.39  23722300.0  0.0  0.0
1  24   J  100002   12  9995000    0    0.00    0.00  23722300.0  0.0  0.0
2  24   J  100004    1   325003   27   34.57   34.90   7076760.0  0.0  0.0
3  24   J  100004   12  9995000    0    0.00    0.00   7076760.0  0.0  0.0
4  24   J  100005    1   325003   27  192.00  196.00  33341142.0  0.0  0.0

   J110  J111       J112        J113
0   0.0   0.0  287932.15  23722300.0
1   0.0   0.0       0.00  23722300.0
2   0.0   0.0  202772.49   7009845.0
3   0.0   0.0       0.00   7009845.0
4   0.0   0.0  170107.87  32660711.0

### Filter CBAM Industries

In [7]:
print(A.columns.tolist())
print(B.columns.tolist())
print(E.columns.tolist())
print(F.columns.tolist())
print(G.columns.tolist())
print(J.columns.tolist())

['yr', 'blk', 'a1', 'a2', 'a3', 'a4', 'a5', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12', 'bonus', 'pf', 'welfare', 'mwdays', 'nwdays', 'wdays', 'costop', 'expshare', 'mult']
['yr', 'blk', 'ab01', 'b02', 'b03', 'b04', 'b05', 'b06f', 'b06t', 'b07', 'b08', 'b09', 'b11']
['yr', 'blk', 'AE01', 'EI1', 'EI3', 'EI4', 'EI5', 'EI6', 'EI7', 'EI8']
['yr', 'blk', 'AF01', 'F1', 'F2A', 'F2B', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13']
['yr', 'blk', 'AG01', 'G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11', 'G12']
['yr', 'blk', 'AJ01', 'J11', 'J13', 'J14', 'J15', 'J16', 'J17', 'J18', 'J19', 'J110', 'J111', 'J112', 'J113']

### Filter CBAM Industries

In [8]:
cbam_codes = [
    23941,23942,
    24101,24102,24103,24104,24105,
    24106,24107,
    24201,24202,24203,24204,
    24209,
    20121,20122,20129,20130
]

cbam_A = A[
    A["a5"].isin(cbam_codes)
]

print(cbam_A.shape)
print(cbam_A["a5"].value_counts())

(2440, 22)
a5
24105    398
24202    283
24103    248
23942    201
24209    186
24102    160
20129    130
24104    111
24201    110
23941    108
24106    106
24203    105
24101    101
20121     94
20122     58
24204     27
24107     14
Name: count, dtype: int64

### Keep Exporters Only

In [9]:
cbam_exporters = cbam_A[
    cbam_A["expshare"] > 0
]

print(cbam_exporters.shape)

(116, 22)

### Employment Block

In [10]:
emp = (
    E.groupby("AE01")
    .sum(numeric_only=True)
    .reset_index()
)

print(emp.head())

     AE01   yr  EI1    EI3  EI4    EI5  EI6    EI7        EI8
0  100002  240   55   7598    0   7598   28   9144  2531000.0
1  100004  240   55   1074    0   1074   16   1746   634160.0
2  100005  240   55   9544    0   9544   34  12266  4529900.0
3  100006  240   55      0  610    610    2    730   228000.0
4  100007  240   55  10236    0  10236   35  10380  4229498.0

### Output Block

In [11]:
output = (
    J.groupby("AJ01")["J113"]
    .sum()
    .reset_index()
)

output.columns = [
    "factory",
    "output_value"
]

print(output.head())

   factory  output_value
0   100002    47444600.0
1   100004    14019690.0
2   100005    65321422.0
3   100007     9521668.0
4   100008    83809372.0

### Merge Everything

In [12]:
master = cbam_exporters.merge(
    emp,
    left_on="a1",
    right_on="AE01",
    how="left"
)

master = master.merge(
    output,
    left_on="a1",
    right_on="factory",
    how="left"
)

print(master.shape)
print(master.head())

(116, 33)
   yr_x blk      a1     a2  a3    a4     a5  a7  a8  a9  ...  yr_y  EI1  \
0    24   A  102179  99999   1  9999  24103   3  99   2  ...   240   55
1    24   A  102189  99999   1  9999  24103   3  99   1  ...   240   55
2    24   A  102196  99999   1  9999  24105   3  99   2  ...   240   55
3    24   A  102227  99999   1  9999  24202   3  99   2  ...   240   55
4    24   A  102958  99999   1  9999  24202   4  99   2  ...   240   55

       EI3  EI4      EI5   EI6      EI7           EI8  factory  output_value
0  1995272    0  1995272  6540  2400568  1.595400e+09   102179  2.669001e+10
1   271752    0   271752   888   334226  2.860385e+08   102189  1.252409e+09
2   321958    0   321958   884   342804  2.840983e+08   102196  5.774041e+09
3   249628    0   249628   818   303168  1.615360e+08   102227  1.694340e+09
4   139762    0   139762   456   168682  2.487659e+08   102958  1.555639e+09

[5 rows x 33 columns]

### Save Excel

In [13]:
master.to_excel(
    "CBAM_Exporters_2023_24.xlsx",
    index=False
)

### Diagnostics

In [14]:
print(master["a5"].value_counts())

print(
    master["expshare"].describe()
)

print(
    master[
        ["a1","a5","expshare"]
    ].sort_values(
        "expshare",
        ascending=False
    ).head(20)
)

a5
24105    29
24202    15
24103    12
24104    12
24209     9
24106     7
24102     7
24101     6
24203     5
24201     4
24107     3
24204     2
20129     2
23941     1
20121     1
23942     1
Name: count, dtype: int64
count    116.000000
mean      24.456897
std       28.239778
min        1.000000
25%        4.000000
50%       14.000000
75%       27.000000
max      100.000000
Name: expshare, dtype: float64
         a1     a5  expshare
90   141677  24104       100
89   141670  24104       100
95   141716  24204       100
102  147990  24102       100
93   141681  24104        95
100  144608  24106        89
61   130122  24209        87
96   141723  24202        85
19   109656  24209        81
73   136558  24106        81
1    102189  24103        76
107  156857  24201        74
108  156861  24202        74
58   130000  24105        70
68   136519  24105        67
101  144650  24209        66
64   132766  24209        64
49   123668  24104        62
24   114268  24103        60
67   136516  24106        58

In [15]:
print(master.isna().sum().sort_values(ascending=False).head(20))

yr_x       0
blk        0
a1         0
a2         0
a3         0
a4         0
a5         0
a7         0
a8         0
a9         0
a10        0
a11        0
a12        0
bonus      0
pf         0
welfare    0
mwdays     0
nwdays     0
wdays      0
costop     0
dtype: int64

In [16]:
print(
    master[
        ["EI3","EI5","EI8","output_value"]
    ].isna().sum()
)

EI3             0
EI5             0
EI8             0
output_value    0
dtype: int64

### FINAL MERGE FILE

In [17]:
import pandas as pd

path = r"C:\Users\hp\OneDrive\Documents\PYTHON"

df19 = pd.read_excel(path + r"\CBAM_Exporters_2019_20.xlsx")
df20 = pd.read_excel(path + r"\CBAM_Exporters_2020_21.xlsx")
df21 = pd.read_excel(path + r"\CBAM_Exporters_2021_22.xlsx")
df22 = pd.read_excel(path + r"\CBAM_Exporters_2022_23.xlsx")
df23 = pd.read_excel(path + r"\CBAM_Exporters_2023_24.xlsx")

print(df19.shape)
print(df20.shape)
print(df21.shape)
print(df22.shape)
print(df23.shape)

(44, 28)
(130, 33)
(150, 33)
(134, 11)
(116, 33)

In [18]:
for i,df in enumerate([df19,df20,df21,df22,df23], start=19):
    print(f"\nYEAR {i}")
    print(df.columns.tolist())

YEAR 19
['yr', 'blk', 'a1', 'a2', 'a3', 'a4', 'a5', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12', 'bonus', 'pf', 'welfare', 'mwdays', 'nwdays', 'wdays', 'costop', 'expshare', 'mult', 'AE01', 'E13', 'E15', 'E18', 'factory', 'output_value']

YEAR 20
['yr_x', 'blk', 'a1', 'a2', 'a3', 'a4', 'a5', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12', 'bonus', 'pf', 'welfare', 'mwdays', 'nwdays', 'wdays', 'costop', 'expshare', 'mult', 'AE01', 'yr_y', 'E11', 'E13', 'E14', 'E15', 'E16', 'E17', 'E18', 'factory', 'output_value']

YEAR 21
['yr_x', 'blk', 'a1', 'a2', 'a3', 'a4', 'a5', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12', 'bonus', 'pf', 'welfare', 'mwdays', 'nwdays', 'wdays', 'costop', 'expshare', 'mult', 'AE01', 'yr_y', 'E11', 'E13', 'E14', 'E15', 'E16', 'E17', 'E18', 'factory', 'output_value']

YEAR 22
['a1', 'a5', 'a7', 'costop', 'expshare', 'mwdays', 'wdays', 'EI3', 'EI5', 'EI8', 'output_value']

YEAR 23
['yr_x', 'blk', 'a1', 'a2', 'a3', 'a4', 'a5', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12', 'bonus', 'pf', 'welfare', 'mwdays', 'nwdays', 'wdays', 'costop', 'expshare', 'mult', 'AE01', 'yr_y', 'EI1', 'EI3', 'EI4', 'EI5', 'EI6', 'EI7', 'EI8', 'factory', 'output_value']

In [19]:
df19 = df19.rename(columns={"E13":"employment","E18":"wages"})
df20 = df20.rename(columns={"E13":"employment","E18":"wages"})
df21 = df21.rename(columns={"E13":"employment","E18":"wages"})
df22 = df22.rename(columns={"EI3":"employment","EI8":"wages"})
df23 = df23.rename(columns={"EI3":"employment","EI8":"wages"})
keep = [
    "a1",
    "a5",
    "a7",
    "costop",
    "expshare",
    "mwdays",
    "wdays",
    "employment",
    "wages",
    "output_value"
]
df19["year"]="2019-20"
df20["year"]="2020-21"
df21["year"]="2021-22"
df22["year"]="2022-23"
df23["year"]="2023-24"
panel = pd.concat(
    [
        df19[keep+["year"]],
        df20[keep+["year"]],
        df21[keep+["year"]],
        df22[keep+["year"]],
        df23[keep+["year"]]
    ],
    ignore_index=True
)

print(panel.shape)

(574, 11)

In [20]:
print(panel.isnull().sum())
print(df19["expshare"].describe())
print((df19["expshare"] > 0).sum())

a1              0
a5              0
a7              0
costop          0
expshare        0
mwdays          0
wdays           0
employment      0
wages           0
output_value    0
year            0
dtype: int64
count     44.000000
mean      23.090909
std       25.026329
min        1.000000
25%        6.500000
50%       14.500000
75%       28.250000
max      100.000000
Name: expshare, dtype: float64
44

### Save a master backup

In [21]:
panel.to_excel(
    r"C:\Users\hp\OneDrive\Documents\PYTHON\CBAM_PANEL_2019_2024.xlsx",
    index=False
)

panel.to_csv(
    r"C:\Users\hp\OneDrive\Documents\PYTHON\CBAM_PANEL_2019_2024.csv",
    index=False
)

print(panel.shape)

(574, 11)

### Create log variables

In [22]:
import numpy as np

panel["ln_output"] = np.log(panel["output_value"] + 1)
panel["ln_employment"] = np.log(panel["employment"] + 1)
panel["ln_cost"] = np.log(panel["costop"] + 1)

panel["export_intensity"] = panel["expshare"] / 100

### Build Carbon Intensity

In [23]:
co2_proxy =coal_qty * coal_factor + electricity_qty * elec_factor + gas_qty * gas_factor
carbon_intensity = co2_proxy / output_value
vulnerability = co2_proxy / costop

NameError: name 'coal_qty' is not defined

### Descriptive tables

In [24]:
panel.groupby("a5")[
    ["output_value","employment","export_intensity"]
].mean()
panel.groupby("year")[
    ["output_value","employment","export_intensity"]
].mean()

         output_value    employment  export_intensity
year
2019-20  1.621564e+10  1.758396e+06          0.230909
2020-21  3.802621e+10  1.886531e+06          0.308462
2021-22  6.390159e+10  2.438889e+06          0.251333
2022-23  3.247014e+10  2.039644e+06          0.266493
2023-24  8.117561e+10  2.558180e+06          0.244569

In [25]:
import pandas as pd
import numpy as np
import matplotlib
import statsmodels.formula.api as smf

print("All good!")

All good!

In [26]:
print(F.columns.tolist())
print(F.head())

['yr', 'blk', 'AF01', 'F1', 'F2A', 'F2B', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13']
   yr blk    AF01   F1      F2A      F2B        F3   F4        F5   F6   F7  \
0  24   F  100002  0.0      0.0      0.0  321794.0  0.0  423220.0  0.0  0.0
1  24   F  100004  0.0  13672.0  15994.0   46480.0  0.0   43601.0  0.0  0.0
2  24   F  100005  0.0   3540.0  33900.0  189107.0  0.0  130295.0  0.0  0.0
3  24   F  100006  0.0      0.0      0.0   28845.0  0.0       0.0  0.0  0.0
4  24   F  100007  0.0      0.0      0.0  470566.0  0.0  170134.0  0.0  0.0

        F8       F9        F10  F11      F12  F13
0      0.0  37500.0  1971914.0  0.0      0.0  0.0
1      0.0  28190.0   179471.0  0.0      0.0  0.0
2  28308.0  10604.0  2191952.0  0.0   1273.0  0.0
3      0.0      0.0        0.0  0.0      0.0  0.0
4      0.0      0.0  2763308.0  0.0  15000.0  0.0

### Check Panel Variables

In [27]:
print(panel.shape)
print(panel.columns.tolist())

(574, 15)
['a1', 'a5', 'a7', 'costop', 'expshare', 'mwdays', 'wdays', 'employment', 'wages', 'output_value', 'year', 'ln_output', 'ln_employment', 'ln_cost', 'export_intensity']

### Create Logs

In [28]:
import numpy as np

panel["ln_output"] = np.log(panel["output_value"])

panel["ln_employment"] = np.log(panel["employment"])

panel["ln_wages"] = np.log(panel["wages"])
panel[
[
"ln_output",
"ln_employment",
"ln_wages"
]
].describe()

        ln_output  ln_employment    ln_wages
count  574.000000     574.000000  574.000000
mean    22.691139      13.057578   19.932486
std      2.036562       1.653831    1.843275
min     15.162209       7.624619   13.724579
25%     21.322737      11.979721   18.784983
50%     22.639406      12.880622   19.664311
75%     24.007636      14.041620   20.954927
max     28.068244      17.815836   25.248297

### Descriptive Statistics

In [29]:
panel[
[
"output_value",
"employment",
"wages",
"expshare"
]
].describe()
desc = panel[
[
"output_value",
"employment",
"wages",
"expshare"
]
].describe()

print(desc)

       output_value    employment         wages    expshare
count  5.740000e+02  5.740000e+02  5.740000e+02  574.000000
mean   5.053921e+10  2.192531e+06  3.167015e+09   26.487805
std    1.448092e+11  6.361963e+06  1.060041e+10   28.637331
min    3.844710e+06  2.048000e+03  9.130800e+05    1.000000
25%    1.821158e+09  1.594875e+05  1.439511e+08    5.000000
50%    6.794701e+09  3.926300e+05  3.468219e+08   15.000000
75%    2.669215e+10  1.253747e+06  1.260723e+09   38.000000
max    1.548402e+12  5.461590e+07  9.229883e+10  100.000000

### Sector-wise Export Share

In [30]:
sector_stats = panel.groupby("a5")[
    "expshare"
].agg(
    ["count","mean","median","max"]
)

print(sector_stats)

       count       mean  median  max
a5
20121     12  30.333333    13.5   95
20129      8  24.000000    24.0   54
23941      8  10.625000     9.0   21
23942      2  28.500000    28.5   42
24101     33  14.393939    10.0   53
24102     32  21.187500     9.5  100
24103     53  16.849057    10.0   88
24104     67  39.686567    25.0  100
24105    138  20.369565    10.0   98
24106     41  38.170732    30.0   95
24107     10  21.500000    24.5   46
24201     23  29.260870    17.0   93
24202     79  23.898734    16.0   99
24203     28  24.678571    22.0   62
24204      3  72.000000    90.0  100
24209     37  47.081081    40.0  100

### Year-wise Export Share

In [31]:
year_stats = panel.groupby("year")[
    "expshare"
].agg(
    ["count","mean","median","max"]
)

print(year_stats)

         count       mean  median  max
year
2019-20     44  23.090909    14.5  100
2020-21    130  30.846154    19.5  100
2021-22    150  25.133333    12.0  100
2022-23    134  26.649254    14.0  100
2023-24    116  24.456897    14.0  100

### Top Exporters

In [32]:
panel[
[
"a1",
"year",
"a5",
"expshare"
]
].sort_values(
    "expshare",
    ascending=False
).head(20)

         a1     year     a5  expshare
7    112473  2019-20  24209       100
548  141677  2023-24  24104       100
547  141670  2023-24  24104       100
422  140706  2022-23  24104       100
423  140715  2022-23  24104       100
553  141716  2023-24  24204       100
290  137821  2021-22  24104       100
285  137493  2021-22  24104       100
396  129411  2022-23  24209       100
147  137278  2020-21  24209       100
560  147990  2023-24  24102       100
304  151179  2021-22  24202        99
441  155857  2022-23  24202        99
95   122242  2020-21  24105        98
391  129282  2022-23  24106        95
551  141681  2023-24  24104        95
287  137502  2021-22  24104        95
294  142088  2021-22  20121        95
425  140720  2022-23  24104        95
293  140370  2021-22  24106        94

### Sector Distribution

In [33]:
print(
panel["a5"]
.value_counts()
)

a5
24105    138
24202     79
24104     67
24103     53
24106     41
24209     37
24101     33
24102     32
24203     28
24201     23
20121     12
24107     10
23941      8
20129      8
24204      3
23942      2
Name: count, dtype: int64

### Year Distribution

In [34]:
print(
panel["year"]
.value_counts()
.sort_index()
)

year
2019-20     44
2020-21    130
2021-22    150
2022-23    134
2023-24    116
Name: count, dtype: int64

### Correlation Matrix

In [35]:
corr = panel[
[
"expshare",
"employment",
"wages",
"output_value"
]
].corr()

print(corr)

              expshare  employment     wages  output_value
expshare      1.000000   -0.108723 -0.123618     -0.105829
employment   -0.108723    1.000000  0.928643      0.813300
wages        -0.123618    0.928643  1.000000      0.785148
output_value -0.105829    0.813300  0.785148      1.000000

### Export Intensity Categories

In [36]:
panel["export_group"] = pd.cut(
    panel["expshare"],
    bins=[0,25,50,75,100],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

print(
panel["export_group"]
.value_counts()
)

export_group
Low          386
Medium        74
Very High     63
High          51
Name: count, dtype: int64

### Save Final Clean Panel

In [37]:
panel.to_excel(
    "CBAM_PANEL_FINAL.xlsx",
    index=False
)

print("Saved")

Saved

In [58]:
print(panel.columns.tolist())

['a1', 'a5', 'a7', 'costop', 'expshare', 'mwdays', 'wdays', 'employment', 'wages', 'output_value', 'year', 'ln_output', 'ln_employment', 'ln_cost', 'export_intensity', 'ln_wages', 'export_group']

### Regression

In [38]:
import statsmodels.formula.api as smf
model1 = smf.ols(
    """
    expshare ~
    ln_output +
    ln_employment +
    ln_wages +
    C(a5) +
    C(year)
    """,
    data=panel
).fit()

print(model1.summary())
model2 = smf.ols(
    """
    export_intensity ~
    ln_output +
    ln_employment +
    ln_wages +
    C(a5) +
    C(year)
    """,
    data=panel
).fit()

print(model2.summary())
sector_year = pd.pivot_table(
    panel,
    values="expshare",
    index="a5",
    columns="year",
    aggfunc="mean"
)

print(sector_year)
panel["size_quartile"] = pd.qcut(
    panel["output_value"],
    4,
    labels=["Q1","Q2","Q3","Q4"]
)

panel.groupby(
    "size_quartile"
)["expshare"].mean()

                            OLS Regression Results
==============================================================================
Dep. Variable:               expshare   R-squared:                       0.162
Model:                            OLS   Adj. R-squared:                  0.129
Method:                 Least Squares   F-statistic:                     4.841
Date:                Mon, 15 Jun 2026   Prob (F-statistic):           9.26e-12
Time:                        10:33:48   Log-Likelihood:                -2688.9
No. Observations:                 574   AIC:                             5424.
Df Residuals:                     551   BIC:                             5524.
Df Model:                          22
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             61.4836     19.862      3.096      0.002      22.470     100.498
C(a5)[T.20129]        -5.2364     12.321     -0.425      0.671     -29.438      18.965
C(a5)[T.23941]       -16.3691     12.344     -1.326      0.185     -40.617       7.878
C(a5)[T.23942]         5.8069     20.528      0.283      0.777     -34.515      46.129
C(a5)[T.24101]       -11.1592      9.235     -1.208      0.227     -29.299       6.980
C(a5)[T.24102]        -4.3478      9.486     -0.458      0.647     -22.981      14.285
C(a5)[T.24103]        -9.8114      8.782     -1.117      0.264     -27.062       7.440
C(a5)[T.24104]        14.0723      8.623      1.632      0.103      -2.865      31.010
C(a5)[T.24105]        -4.5416      8.301     -0.547      0.585     -20.847      11.764
C(a5)[T.24106]         9.4108      8.913      1.056      0.292      -8.097      26.919
C(a5)[T.24107]        -7.8766     11.657     -0.676      0.500     -30.773      15.020
C(a5)[T.24201]        -1.5524      9.666     -0.161      0.872     -20.540      17.435
C(a5)[T.24202]        -2.6470      8.467     -0.313      0.755     -19.279      13.985
C(a5)[T.24203]         4.0387      9.471      0.426      0.670     -14.566      22.643
C(a5)[T.24204]        41.7872     17.509      2.387      0.017       7.394      76.181
C(a5)[T.24209]        19.1445      9.012      2.124      0.034       1.443      36.846
C(year)[T.2020-21]    11.2967      4.775      2.366      0.018       1.917      20.676
C(year)[T.2021-22]     5.4371      4.741      1.147      0.252      -3.875      14.749
C(year)[T.2022-23]     2.3253      4.730      0.492      0.623      -6.966      11.616
C(year)[T.2023-24]     4.6487      4.930      0.943      0.346      -5.035      14.332
ln_output             -5.4747      1.359     -4.027      0.000      -8.145      -2.805
ln_employment          0.9286      2.622      0.354      0.723      -4.221       6.078
ln_wages               3.5824      2.563      1.398      0.163      -1.453       8.618
==============================================================================
Omnibus:                       77.859   Durbin-Watson:                   1.412
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              107.032
Skew:                           1.033   Prob(JB):                     5.73e-24
Kurtosis:                       3.450   Cond. No.                         997.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       export_intensity   R-squared:                       0.162
Model:                            OLS   Adj. R-squared:                  0.129
Method:                 Least Squares   F-statistic:                     4.841
Date:                Mon, 15 Jun 2026   Prob (F-statistic):           9.26e-12
Time:                        10:33:48   Log-Likelihood:                -45.492
No. Observations:                 574   AIC:                             137.0
Df Residuals:                     551   BIC:                             237.1
Df Model:                          22
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              0.6148      0.199      3.096      0.002       0.225       1.005
C(a5)[T.20129]        -0.0524      0.123     -0.425      0.671      -0.294       0.190
C(a5)[T.23941]        -0.1637      0.123     -1.326      0.185      -0.406       0.079
C(a5)[T.23942]         0.0581      0.205      0.283      0.777      -0.345       0.461
C(a5)[T.24101]        -0.1116      0.092     -1.208      0.227      -0.293       0.070
C(a5)[T.24102]        -0.0435      0.095     -0.458      0.647      -0.230       0.143
C(a5)[T.24103]        -0.0981      0.088     -1.117      0.264      -0.271       0.074
C(a5)[T.24104]         0.1407      0.086      1.632      0.103      -0.029       0.310
C(a5)[T.24105]        -0.0454      0.083     -0.547      0.585      -0.208       0.118
C(a5)[T.24106]         0.0941      0.089      1.056      0.292      -0.081       0.269
C(a5)[T.24107]        -0.0788      0.117     -0.676      0.500      -0.308       0.150
C(a5)[T.24201]        -0.0155      0.097     -0.161      0.872      -0.205       0.174
C(a5)[T.24202]        -0.0265      0.085     -0.313      0.755      -0.193       0.140
C(a5)[T.24203]         0.0404      0.095      0.426      0.670      -0.146       0.226
C(a5)[T.24204]         0.4179      0.175      2.387      0.017       0.074       0.762
C(a5)[T.24209]         0.1914      0.090      2.124      0.034       0.014       0.368
C(year)[T.2020-21]     0.1130      0.048      2.366      0.018       0.019       0.207
C(year)[T.2021-22]     0.0544      0.047      1.147      0.252      -0.039       0.147
C(year)[T.2022-23]     0.0233      0.047      0.492      0.623      -0.070       0.116
C(year)[T.2023-24]     0.0465      0.049      0.943      0.346      -0.050       0.143
ln_output             -0.0547      0.014     -4.027      0.000      -0.081      -0.028
ln_employment          0.0093      0.026      0.354      0.723      -0.042       0.061
ln_wages               0.0358      0.026      1.398      0.163      -0.015       0.086
==============================================================================
Omnibus:                       77.859   Durbin-Watson:                   1.412
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              107.032
Skew:                           1.033   Prob(JB):                     5.73e-24
Kurtosis:                       3.450   Cond. No.                         997.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
year     2019-20    2020-21    2021-22    2022-23    2023-24
a5
20121        NaN  13.200000  76.000000  35.500000   4.000000
20129  54.000000  31.000000  17.333333  16.000000  19.500000
23941  18.500000   4.500000   6.000000        NaN  21.000000
23942        NaN        NaN  42.000000        NaN  15.000000
24101  11.250000  12.666667  10.714286  18.000000  19.166667
24102   3.500000  43.444444  10.600000   8.888889  21.000000
24103  16.000000  24.166667   5.818182  16.083333  20.833333
24104  38.166667  37.666667  40.555556  39.315789  41.750000
24105  13.125000  35.567568  15.594595  16.148148  13.000000
24106  32.000000  33.142857  36.166667  45.272727  39.000000
24107  26.000000  46.000000  27.333333  10.000000  13.666667
24201  35.500000  26.375000  34.285714   6.000000  34.750000
24202  18.500000  20.125000  25.590909  26.090909  23.666667
24203  18.000000  24.750000  33.888889  22.125000  14.800000
24204        NaN  90.000000        NaN        NaN  63.000000
24209  54.000000  56.833333  38.300000  55.000000  40.000000

size_quartile
Q1    34.083333
Q2    26.237762
Q3    27.853147
Q4    17.784722
Name: expshare, dtype: float64

### Save current results.

In [39]:
sector_year.to_excel("sector_year_exports.xlsx")
sector_stats.to_excel("sector_stats.xlsx")

### Verify whether you have Block I

In [40]:
import pandas as pd

I = pd.read_csv(r"C:\Users\hp\Downloads\CBAM PROJECT\23-24\ASI_DATA_2023_24_CSV\blkI202324.csv")
print(I.columns.tolist())
print(I.head())

['yr', 'blk', 'AI01', 'II1', 'II3', 'II4', 'II5', 'II6', 'II7']
   yr blk    AI01  II1      II3  II4          II5           II6         II7
0  24   I  100067    1   164000    9  24186955.67  6.979630e+09      288.57
1  24   I  100067    7  9994000    0         0.00  6.979630e+09        0.00
2  24   I  100076    1   149100   27       416.00  1.489876e+08   358143.24
3  24   I  100076    7  9994000    0         0.00  1.489876e+08        0.00
4  24   I  100084    1   165900   27        15.56  1.587046e+07  1019952.70

In [41]:
print(sorted(I["II3"].unique())[:100])

[np.int64(111100), np.int64(112100), np.int64(112200), np.int64(115200), np.int64(117100), np.int64(117200), np.int64(121300), np.int64(121500), np.int64(123100), np.int64(123400), np.int64(123500), np.int64(124900), np.int64(125300), np.int64(125900), np.int64(126000), np.int64(129003), np.int64(129099), np.int64(131400), np.int64(131900), np.int64(134400), np.int64(134900), np.int64(135300), np.int64(136000), np.int64(137100), np.int64(137200), np.int64(137400), np.int64(137500), np.int64(137600), np.int64(137900), np.int64(139900), np.int64(141200), np.int64(143200), np.int64(144200), np.int64(144400), np.int64(144500), np.int64(144999), np.int64(145000), np.int64(149100), np.int64(161001), np.int64(161099), np.int64(162099), np.int64(164000), np.int64(165100), np.int64(165200), np.int64(165300), np.int64(165400), np.int64(165500), np.int64(165600), np.int64(165700), np.int64(165900), np.int64(169000), np.int64(170103), np.int64(170199), np.int64(170301), np.int64(170399), np.int64(170400), np.int64(170500), np.int64(170901), np.int64(170903), np.int64(170999), np.int64(192100), np.int64(192200), np.int64(192901), np.int64(192999), np.int64(193007), np.int64(193008), np.int64(193015), np.int64(193099), np.int64(195000), np.int64(196100), np.int64(196200), np.int64(196300), np.int64(197000), np.int64(221100), np.int64(231000), np.int64(241100), np.int64(291000), np.int64(294100), np.int64(294200), np.int64(294300), np.int64(294401), np.int64(294402), np.int64(295100), np.int64(295200), np.int64(295300), np.int64(295400), np.int64(311000), np.int64(312001), np.int64(312099), np.int64(321901), np.int64(321902), np.int64(321903), np.int64(321907), np.int64(321908), np.int64(321999), np.int64(322000), np.int64(324900), np.int64(325001), np.int64(412000), np.int64(421004)]

In [42]:
fuel23 = (
    I.groupby("II3")["II6"]
    .sum()
    .sort_values(ascending=False)
)

fuel23.head(30)

II3
9994000    2.598820e+13
1201000    8.868019e+12
1639001    2.830975e+12
1101002    1.579233e+12
9922100    7.075126e+11
1202003    5.073102e+11
2153500    4.125258e+11
3337000    3.169822e+11
4740100    3.140558e+11
1424004    2.927773e+11
1421000    2.907483e+11
4912999    2.709245e+11
4716000    2.554632e+11
3411071    2.186226e+11
3934003    2.059910e+11
2153100    2.033371e+11
1632001    1.711409e+11
3936102    1.652341e+11
1101006    1.363360e+11
3711500    1.336756e+11
2153300    1.323608e+11
4715002    1.259493e+11
3423200    1.216811e+11
4121101    1.101974e+11
4713099    1.026298e+11
1639006    9.832658e+10
4621500    9.642674e+10
3411049    9.414835e+10
1202001    9.149028e+10
1101003    8.836581e+10
Name: II6, dtype: float64

In [43]:
panel["labour_productivity"] = (
    panel["output_value"] /
    panel["employment"]
)

panel["wage_per_worker"] = (
    panel["wages"] /
    panel["employment"]
)

panel["profit_proxy"] = (
    panel["output_value"] -
    panel["costop"]
)

In [44]:
import statsmodels.formula.api as smf

m1 = smf.ols(
    "export_intensity ~ ln_output + ln_employment",
    data=panel
).fit()

print(m1.summary())
m2 = smf.ols(
    "export_intensity ~ ln_output + ln_employment + C(a5)",
    data=panel
).fit()

print(m2.summary())
m3 = smf.ols(
    "export_intensity ~ ln_output + ln_employment + ln_wages + C(a5) + C(year)",
    data=panel
).fit()

print(m3.summary())
m4 = smf.ols(
    "export_intensity ~ labour_productivity + wage_per_worker + C(a5) + C(year)",
    data=panel
).fit()

print(m4.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       export_intensity   R-squared:                       0.043
Model:                            OLS   Adj. R-squared:                  0.039
Method:                 Least Squares   F-statistic:                     12.73
Date:                Mon, 15 Jun 2026   Prob (F-statistic):           3.92e-06
Time:                        10:34:04   Log-Likelihood:                -83.691
No. Observations:                 574   AIC:                             173.4
Df Residuals:                     571   BIC:                             186.4
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.9526      0.137      6.959      0.000       0.684       1.221
ln_output        -0.0408      0.011     -3.602      0.000      -0.063      -0.019
ln_employment     0.0182      0.014      1.304      0.193      -0.009       0.046
==============================================================================
Omnibus:                       94.336   Durbin-Watson:                   1.394
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              139.780
Skew:                           1.190   Prob(JB):                     4.44e-31
Kurtosis:                       3.421   Cond. No.                         308.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       export_intensity   R-squared:                       0.146
Model:                            OLS   Adj. R-squared:                  0.120
Method:                 Least Squares   F-statistic:                     5.589
Date:                Mon, 15 Jun 2026   Prob (F-statistic):           9.76e-12
Time:                        10:34:05   Log-Likelihood:                -50.930
No. Observations:                 574   AIC:                             137.9
Df Residuals:                     556   BIC:                             216.2
Df Model:                          17
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.7915      0.162      4.895      0.000       0.474       1.109
C(a5)[T.20129]    -0.0841      0.123     -0.685      0.494      -0.325       0.157
C(a5)[T.23941]    -0.1880      0.123     -1.529      0.127      -0.430       0.054
C(a5)[T.23942]     0.0229      0.206      0.112      0.911      -0.381       0.427
C(a5)[T.24101]    -0.1482      0.091     -1.631      0.103      -0.327       0.030
C(a5)[T.24102]    -0.0886      0.092     -0.967      0.334      -0.269       0.091
C(a5)[T.24103]    -0.1371      0.086     -1.593      0.112      -0.306       0.032
C(a5)[T.24104]     0.0970      0.084      1.151      0.250      -0.069       0.263
C(a5)[T.24105]    -0.0782      0.082     -0.958      0.338      -0.238       0.082
C(a5)[T.24106]     0.0605      0.088      0.684      0.494      -0.113       0.234
C(a5)[T.24107]    -0.1195      0.115     -1.036      0.301      -0.346       0.107
C(a5)[T.24201]    -0.0340      0.096     -0.354      0.724      -0.223       0.155
C(a5)[T.24202]    -0.0638      0.083     -0.766      0.444      -0.227       0.100
C(a5)[T.24203]    -0.0033      0.094     -0.035      0.972      -0.188       0.181
C(a5)[T.24204]     0.4077      0.175      2.330      0.020       0.064       0.751
C(a5)[T.24209]     0.1582      0.089      1.769      0.077      -0.017       0.334
ln_output         -0.0416      0.012     -3.592      0.000      -0.064      -0.019
ln_employment      0.0344      0.014      2.413      0.016       0.006       0.062
==============================================================================
Omnibus:                       80.552   Durbin-Watson:                   1.393
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              111.962
Skew:                           1.055   Prob(JB):                     4.87e-25
Kurtosis:                       3.478   Cond. No.                         761.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       export_intensity   R-squared:                       0.162
Model:                            OLS   Adj. R-squared:                  0.129
Method:                 Least Squares   F-statistic:                     4.841
Date:                Mon, 15 Jun 2026   Prob (F-statistic):           9.26e-12
Time:                        10:34:05   Log-Likelihood:                -45.492
No. Observations:                 574   AIC:                             137.0
Df Residuals:                     551   BIC:                             237.1
Df Model:                          22
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              0.6148      0.199      3.096      0.002       0.225       1.005
C(a5)[T.20129]        -0.0524      0.123     -0.425      0.671      -0.294       0.190
C(a5)[T.23941]        -0.1637      0.123     -1.326      0.185      -0.406       0.079
C(a5)[T.23942]         0.0581      0.205      0.283      0.777      -0.345       0.461
C(a5)[T.24101]        -0.1116      0.092     -1.208      0.227      -0.293       0.070
C(a5)[T.24102]        -0.0435      0.095     -0.458      0.647      -0.230       0.143
C(a5)[T.24103]        -0.0981      0.088     -1.117      0.264      -0.271       0.074
C(a5)[T.24104]         0.1407      0.086      1.632      0.103      -0.029       0.310
C(a5)[T.24105]        -0.0454      0.083     -0.547      0.585      -0.208       0.118
C(a5)[T.24106]         0.0941      0.089      1.056      0.292      -0.081       0.269
C(a5)[T.24107]        -0.0788      0.117     -0.676      0.500      -0.308       0.150
C(a5)[T.24201]        -0.0155      0.097     -0.161      0.872      -0.205       0.174
C(a5)[T.24202]        -0.0265      0.085     -0.313      0.755      -0.193       0.140
C(a5)[T.24203]         0.0404      0.095      0.426      0.670      -0.146       0.226
C(a5)[T.24204]         0.4179      0.175      2.387      0.017       0.074       0.762
C(a5)[T.24209]         0.1914      0.090      2.124      0.034       0.014       0.368
C(year)[T.2020-21]     0.1130      0.048      2.366      0.018       0.019       0.207
C(year)[T.2021-22]     0.0544      0.047      1.147      0.252      -0.039       0.147
C(year)[T.2022-23]     0.0233      0.047      0.492      0.623      -0.070       0.116
C(year)[T.2023-24]     0.0465      0.049      0.943      0.346      -0.050       0.143
ln_output             -0.0547      0.014     -4.027      0.000      -0.081      -0.028
ln_employment          0.0093      0.026      0.354      0.723      -0.042       0.061
ln_wages               0.0358      0.026      1.398      0.163      -0.015       0.086
==============================================================================
Omnibus:                       77.859   Durbin-Watson:                   1.412
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              107.032
Skew:                           1.033   Prob(JB):                     5.73e-24
Kurtosis:                       3.450   Cond. No.                         997.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       export_intensity   R-squared:                       0.141
Model:                            OLS   Adj. R-squared:                  0.108
Method:                 Least Squares   F-statistic:                     4.303
Date:                Mon, 15 Jun 2026   Prob (F-statistic):           1.12e-09
Time:                        10:34:05   Log-Likelihood:                -52.699
No. Observations:                 574   AIC:                             149.4
Df Residuals:                     552   BIC:                             245.2
Df Model:                          21
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               0.2712      0.096      2.813      0.005       0.082       0.461
C(a5)[T.20129]         -0.0465      0.126     -0.369      0.712      -0.294       0.201
C(a5)[T.23941]         -0.1871      0.125     -1.494      0.136      -0.433       0.059
C(a5)[T.23942]          0.0212      0.208      0.102      0.919      -0.387       0.430
C(a5)[T.24101]         -0.1486      0.094     -1.575      0.116      -0.334       0.037
C(a5)[T.24102]         -0.0861      0.096     -0.898      0.370      -0.274       0.102
C(a5)[T.24103]         -0.1206      0.090     -1.338      0.181      -0.298       0.056
C(a5)[T.24104]          0.1075      0.089      1.214      0.225      -0.066       0.281
C(a5)[T.24105]         -0.0863      0.084     -1.022      0.307      -0.252       0.080
C(a5)[T.24106]          0.0913      0.092      0.994      0.321      -0.089       0.272
C(a5)[T.24107]         -0.0729      0.119     -0.611      0.541      -0.307       0.161
C(a5)[T.24201]         -0.0076      0.100     -0.076      0.939      -0.203       0.188
C(a5)[T.24202]         -0.0509      0.087     -0.583      0.560      -0.222       0.121
C(a5)[T.24203]          0.0042      0.098      0.042      0.966      -0.188       0.196
C(a5)[T.24204]          0.4349      0.176      2.465      0.014       0.088       0.781
C(a5)[T.24209]          0.1840      0.092      1.991      0.047       0.003       0.366
C(year)[T.2020-21]      0.0844      0.048      1.769      0.077      -0.009       0.178
C(year)[T.2021-22]      0.0181      0.047      0.386      0.700      -0.074       0.110
C(year)[T.2022-23]      0.0179      0.048      0.376      0.707      -0.076       0.111
C(year)[T.2023-24]      0.0101      0.049      0.208      0.835      -0.085       0.106
labour_productivity -4.918e-07   2.97e-07     -1.658      0.098   -1.07e-06     9.1e-08
wage_per_worker      4.575e-07   1.59e-05      0.029      0.977   -3.07e-05    3.17e-05
==============================================================================
Omnibus:                       79.287   Durbin-Watson:                   1.421
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              110.013
Skew:                           1.055   Prob(JB):                     1.29e-24
Kurtosis:                       3.384   Cond. No.                     1.67e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.67e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [45]:
import statsmodels.formula.api as smf

robust = smf.ols(
    "export_intensity ~ ln_output + ln_employment + ln_wages + C(a5) + C(year)",
    data=panel
).fit(cov_type="HC3")

print(robust.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       export_intensity   R-squared:                       0.162
Model:                            OLS   Adj. R-squared:                  0.129
Method:                 Least Squares   F-statistic:                     4.892
Date:                Mon, 15 Jun 2026   Prob (F-statistic):           6.28e-12
Time:                        10:34:07   Log-Likelihood:                -45.492
No. Observations:                 574   AIC:                             137.0
Df Residuals:                     551   BIC:                             237.1
Df Model:                          22
Covariance Type:                  HC3
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              0.6148      0.234      2.625      0.009       0.156       1.074
C(a5)[T.20129]        -0.0524      0.122     -0.428      0.669      -0.292       0.187
C(a5)[T.23941]        -0.1637      0.100     -1.641      0.101      -0.359       0.032
C(a5)[T.23942]         0.0581      0.198      0.293      0.770      -0.331       0.447
C(a5)[T.24101]        -0.1116      0.097     -1.149      0.251      -0.302       0.079
C(a5)[T.24102]        -0.0435      0.112     -0.387      0.699      -0.264       0.177
C(a5)[T.24103]        -0.0981      0.099     -0.990      0.322      -0.292       0.096
C(a5)[T.24104]         0.1407      0.103      1.370      0.171      -0.061       0.342
C(a5)[T.24105]        -0.0454      0.095     -0.477      0.633      -0.232       0.141
C(a5)[T.24106]         0.0941      0.107      0.882      0.378      -0.115       0.303
C(a5)[T.24107]        -0.0788      0.103     -0.763      0.446      -0.281       0.124
C(a5)[T.24201]        -0.0155      0.118     -0.132      0.895      -0.246       0.215
C(a5)[T.24202]        -0.0265      0.098     -0.270      0.787      -0.218       0.165
C(a5)[T.24203]         0.0404      0.099      0.409      0.683      -0.153       0.234
C(a5)[T.24204]         0.4179      0.296      1.410      0.159      -0.163       0.999
C(a5)[T.24209]         0.1914      0.111      1.731      0.083      -0.025       0.408
C(year)[T.2020-21]     0.1130      0.044      2.581      0.010       0.027       0.199
C(year)[T.2021-22]     0.0544      0.042      1.298      0.194      -0.028       0.136
C(year)[T.2022-23]     0.0233      0.042      0.549      0.583      -0.060       0.106
C(year)[T.2023-24]     0.0465      0.044      1.051      0.293      -0.040       0.133
ln_output             -0.0547      0.016     -3.439      0.001      -0.086      -0.024
ln_employment          0.0093      0.030      0.312      0.755      -0.049       0.068
ln_wages               0.0358      0.030      1.176      0.239      -0.024       0.096
==============================================================================
Omnibus:                       77.859   Durbin-Watson:                   1.412
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              107.032
Skew:                           1.033   Prob(JB):                     5.73e-24
Kurtosis:                       3.450   Cond. No.                         997.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)